### ISSUE TITLE
At the first start "btoa is not defined"

### ISSUE THREAD

**Issue by reualex** [burhanahmeed/vue-modal-2#11]
When you running your nuxt application at the first time, get error: `[Vue warn]: Error in beforeCreate hook: "ReferenceError: btoa is not defined"`
After save any component - the error disappears.

**Comment by burhanahmeed** [comment]
BTW, my package didn't use btoa. I am not sure about this warning

**Comment by reualex** [comment]
> BTW, my package didn't use btoa. I am not sure about this warning

Yep, me too. But If I don't use plugin this error dissapear. 

` [Vue warn]: Error in beforeCreate hook: "ReferenceError: btoa is not defined"                                                                                             09:57:11

found in

       <VueModal2>
       <ModalsWindows> at components/Common/ModalsWindows/index.vue
         <DefaultLayout> at layouts/default.vue
           <Root>`

It is full error message

**Comment by burhanahmeed** [comment]
are you using Nuxt or just Vue? which version?

**Comment by TuanHarry** [comment]
I'm using nuxt version 2.15.3

**Comment by TuanHarry** [comment]
solution : wrapped with `<client-only> </client-only>` (previously` no-ssr)

**Comment by burhanahmeed** [comment]
yes for Nuxt you need to wrap it https://initbase.github.io/vue-modal-2/installation/vue-2x.html#nuxt
