### ISSUE TITLE
Property '$vm2' does not exist on type

### ISSUE THREAD

**Issue by avpavp** [burhanahmeed/vue-modal-2#2]
Hi

Thanks for your component.  

I'm using it successfully in debug mode.  While in debug mode I do get an error though:

Property '$vm2' does not exist on type 'CombinedVueInstance<Vue, PageState....

While in debug mode this still runs correctly, but if I try and do yarn build, it fails with the same error.

Any ideas?

Thanks

**Comment by burhanahmeed** [comment]
which version are you using?

**Comment by burhanahmeed** [comment]
v1.1.8 should be fine. 

Tested it using debug mode and build mode no error prompted in console.

**Comment by avpavp** [comment]
Hmmm... I was using v1.1.6.  upgraded to 1.1.8, still getting the same error...  Must be something else about my config...?
